baseURL: "https://heyyviv.github.io/"
title: Vivek's Field Notes
languageCode: en
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Vivek's Field Notes
  description: "A write up of my field notes"
  keywords: [Blog, Portfolio, PaperMod]
  author: Vivek Das
  images: ["/images/"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    favicon: "/images/favicon.png"

  label:
    text: "Home"

  profileMode:
    enabled: false
    title: Vivek's Field Notes
    subtitle: "A curious engineer navigating the world of code"
    imageUrl: "/images/profile.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Vivek Das
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Hi there \U0001F44B "
    Content: "I'm Vivek, a curious engineer navigating the world of code, systems, and ideas. This blog is my notebook for experiments, learnings, and technical deep dives."

  socialIcons:
    - name: x
      url: "https://x.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/"

  analytics:
    google:
      SiteVerificationTag: "G-9XGNLFNGJ7"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false