baseURL: 'https://heyy.github.io/'
languageCode: 'en-us'
title: "Vivek's Field Notes"
theme: 'PaperMod'

params:
  enableRobotsTXT: true
  homeInfoParams:
    Title: Hi there wave
    Content: "I'm Vivek, a curious engineer navigating the world of code, systems, and ideas. This blog is my notebook for experiments, learnings, and technical deep dives."

  socialIcons: # optional
    - name: "X"
      url: "https://x.com/kanna_180512"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/vivek-das-1631ab191/"

  outputs:
    home:
      - HTML
      - RSS
      - JSON # necessary for search

  analytics:
    google:
      SiteVerificationTag: "G-9XGNLFNGJ7"