name: Build and Deploy Hugo Site

on:
  push:
    branches: [main]  # Trigger this on push to main branch
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write  # Needed to push to the repo (main branch)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo Site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main  # Deploy to the main branch
          folder: public  # Hugo outputs to 'public' by default
          clean: true  # Optional: removes existing files before deploy
