jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: public
